export type CapabilityName = 'monitor' | 'csv_logging' | 'set_run_request' | 'set_balancing_request' | 'acknowledge_faults' | 'get_rtc' | 'get_device_info' | 'read_register' | 'wifi_configuration' | 'diagnostic_log_download' | 'raw_terminal' | 'firmware_update'
export type Capabilities = Record<CapabilityName, boolean>
export type ServiceName = 'set_run_request' | 'set_balancing_request' | 'acknowledge_faults' | 'get_rtc' | 'get_device_info' | 'read_register'
export type ServiceArguments = { set_run_request: { requested: boolean }; set_balancing_request: { requested: boolean }; acknowledge_faults: Record<string, never>; get_rtc: Record<string, never>; get_device_info: Record<string, never>; read_register: { slave_index: number; register: number } }
export type ServiceResult = 'ok' | 'denied' | 'invalid' | 'busy' | 'usb_host_active' | 'transport_error'
export type ServiceResponse = { request_id: string; service: ServiceName; result: ServiceResult; data?: { slave_index?: number; register?: number; value?: number; unix_time_s?: number; firmware_version_packed?: number } }
export type Status = { bms_state: number; hv_state: number; flags: number; slave_count: number; bms_active_errors: number; bms_latched_errors: number; hv_active_errors: number; hv_latched_errors: number; warnings: number; uptime_ms: number; measurements_fresh: boolean; run_request: boolean; balancing_request: boolean; soc_valid: boolean }
export type Snapshot = { status: Status; pack: { pack_voltage_uV: number; pack_current_raw: number; soc_raw: number; min_cell_uV: number; max_cell_uV: number; min_ntc_raw: number; max_ntc_raw: number; min_ic_raw: number; max_ic_raw: number }; cells: Array<{ slave_index: number; balance_mask: number; cell_voltage_uV: number[] }>; temperatures: Array<{ slave_index: number; ntc_raw: number[]; ic_temp_raw: number }> }
export type WifiNetwork = { ssid: string; rssi: number; secure: boolean }
export type WifiConfigurationResponse = { request_id: string; result: 'accepted' | 'error' | 'transport_error' }
export type WifiScanResponse = { request_id: string; result: 'ok' | 'busy' | 'rate_limited' | 'unavailable' | 'transport_error'; networks?: WifiNetwork[] }
export type FirmwareUpdateStage = 'idle' | 'upload' | 'validate' | 'restart' | 'handoff' | 'rom' | 'erase' | 'program' | 'verify' | 'complete'
export type FirmwareUpdateStatus = { phase: 'idle' | 'uploading' | 'installing' | 'complete' | 'failed'; target: 'gateway' | 'stm32'; stage: FirmwareUpdateStage; received_bytes: number; expected_bytes: number; progress_bytes: number; version: string; detail: string }
export type GatewayStatus = { gateway_version?: string; wifi_state: 'provisioning' | 'connecting' | 'connected' | 'recovery' | 'unavailable'; wifi_ssid?: string; setup_ap: { active: boolean; ssid?: string; address?: string }; uart_state: 'healthy' | 'lost' | 'starting'; mqtt_state: 'unavailable' | 'connecting' | 'connected' | 'lost'; time_sync: { state: 'waiting_for_network' | 'waiting_for_ntp' | 'waiting_for_stm32' | 'synchronized'; last_sync_unix_s?: number }; diagnostic_log: { available: boolean; bytes: number }; firmware_update: FirmwareUpdateStatus }
export type ConnectionState = 'disconnected' | 'connecting' | 'connected'
export interface BmsTransport { readonly label: string; connect(): Promise<void>; disconnect(): void; getConnectionState(): ConnectionState; getCapabilities(): Capabilities; request<S extends ServiceName>(service: S, args: ServiceArguments[S]): Promise<ServiceResponse>; configureWifi(ssid: string, password: string): Promise<WifiConfigurationResponse>; scanWifi(): Promise<WifiScanResponse>; onBmsStatus(listener: (status: Status) => void): () => void; onSnapshot(listener: (snapshot: Snapshot) => void): () => void; onEvent(listener: (event: { event_id: number; value: number; gateway_uptime_ms?: number }) => void): () => void; onState(listener: (state: ConnectionState, gateway?: GatewayStatus) => void): () => void; sendRaw?(line: string): Promise<void>; onRaw?(listener: (line: string) => void): () => void }
export const unavailableCapabilities = (): Capabilities => ({ monitor: true, csv_logging: true, set_run_request: true, set_balancing_request: true, acknowledge_faults: true, get_rtc: true, get_device_info: true, read_register: true, wifi_configuration: false, diagnostic_log_download: false, raw_terminal: false, firmware_update: false })
