export type CapabilityName = 'monitor' | 'csv_logging' | 'set_run_request' | 'set_balancing_enabled' | 'acknowledge_faults' | 'get_rtc' | 'get_device_info' | 'read_register' | 'get_diagnostic_report' | 'runtime_configuration' | 'wifi_configuration' | 'mqtt_configuration' | 'diagnostic_log_download' | 'raw_terminal' | 'firmware_update'
export type Capabilities = Record<CapabilityName, boolean>
export type ServiceName = 'set_run_request' | 'set_balancing_enabled' | 'acknowledge_faults' | 'get_rtc' | 'get_device_info' | 'read_register' | 'get_config' | 'set_config' | 'get_diagnostic_report'
export type RuntimeConfiguration = { reason: 'valid' | 'blank' | 'version_mismatch' | 'corrupt'; expected_version: number; stored_version: number; slave_count: number; current_sense_slave: number; shunt_resistance_uohm: number; battery_capacity_mah: number; invert_current: boolean; balance_enabled: boolean; startup_diagnostics: boolean }
export type BccDiagnosticReport = { slave_index: number; cid: number; failed_checks: number; status_code: number; failed_diagnostic: number }
export type ServiceArguments = { set_run_request: { requested: boolean }; set_balancing_enabled: { enabled: boolean }; acknowledge_faults: Record<string, never>; get_rtc: Record<string, never>; get_device_info: Record<string, never>; read_register: { slave_index: number; register: number }; get_config: Record<string, never>; set_config: Omit<RuntimeConfiguration, 'reason' | 'expected_version' | 'stored_version'>; get_diagnostic_report: { slave_index: number } }
export type ServiceResult = 'ok' | 'denied' | 'invalid' | 'busy' | 'usb_host_active' | 'transport_error'
export type ServiceResponse = { request_id: string; service: ServiceName; result: ServiceResult; data?: { slave_index?: number; register?: number; value?: number; unix_time_s?: number; firmware_version_packed?: number } & Partial<RuntimeConfiguration> & Partial<BccDiagnosticReport> }
export type Status = { bms_state: number; hv_state: number; flags: number; slave_count: number; bms_active_errors: number; bms_latched_errors: number; hv_active_errors: number; hv_latched_errors: number; warnings: number; uptime_ms: number; measurements_fresh: boolean; run_request: boolean; balancing_enabled: boolean; soc_valid: boolean; current_sensing_enabled: boolean; soc_last_calibration_unix_s?: number }
export type Snapshot = { status: Status; pack: { pack_voltage_uV: number; pack_current_raw: number; soc_raw: number; min_cell_uV: number; max_cell_uV: number; min_ntc_raw: number; max_ntc_raw: number; min_ic_raw: number; max_ic_raw: number }; hv_voltages?: { valid: boolean; bat_plus_uV: number; load_plus_uV: number }; cells: Array<{ slave_index: number; balance_mask: number; cell_voltage_uV: number[] }>; temperatures: Array<{ slave_index: number; ntc_raw: number[]; ic_temp_raw: number }> }
export type WifiNetwork = { ssid: string; rssi: number; secure: boolean }
export type WifiConfigurationResponse = { request_id: string; result: 'accepted' | 'error' | 'transport_error' }
export type MqttConfigurationResponse = { request_id: string; result: 'accepted' | 'error' | 'transport_error' }
export type WifiScanResponse = { request_id: string; result: 'ok' | 'busy' | 'rate_limited' | 'unavailable' | 'transport_error'; networks?: WifiNetwork[] }
export type FirmwareUpdateStage = 'idle' | 'upload' | 'validate' | 'restart' | 'handoff' | 'rom' | 'erase' | 'program' | 'verify' | 'complete'
export type FirmwareUpdateStatus = { phase: 'idle' | 'uploading' | 'installing' | 'complete' | 'failed'; target: 'gateway' | 'stm32'; stage: FirmwareUpdateStage; received_bytes: number; expected_bytes: number; progress_bytes: number; version: string; detail: string }
export type GatewayStatus = { gateway_version?: string; gateway_build_id?: string; gateway_uptime_ms: number; gateway_partition?: string; wifi_state: 'provisioning' | 'connecting' | 'connected' | 'recovery' | 'unavailable'; wifi_ssid?: string; setup_ap: { active: boolean; ssid?: string; address?: string }; uart_state: 'healthy' | 'lost' | 'starting'; mqtt_state: 'unavailable' | 'connecting' | 'connected' | 'lost'; mqtt: { configured: boolean; host?: string; port?: number; username?: string }; time_sync: { state: 'waiting_for_network' | 'waiting_for_ntp' | 'waiting_for_stm32' | 'synchronized'; last_sync_unix_s?: number }; diagnostic_log: { available: boolean; bytes: number }; firmware_update: FirmwareUpdateStatus }
export type ConnectionState = 'disconnected' | 'connecting' | 'connected'
export type ControllerEvent = { event_id: number; value: number; gateway_uptime_ms?: number }
export type RecordedControllerEvent = ControllerEvent & { observed_at_ms: number }
export interface BmsTransport { readonly label: string; connect(): Promise<void>; disconnect(): void; getConnectionState(): ConnectionState; getCapabilities(): Capabilities; request<S extends ServiceName>(service: S, args: ServiceArguments[S]): Promise<ServiceResponse>; configureWifi(ssid: string, password: string): Promise<WifiConfigurationResponse>; configureMqtt(host: string, port: number, username: string, password: string): Promise<MqttConfigurationResponse>; scanWifi(): Promise<WifiScanResponse>; onBmsStatus(listener: (status: Status) => void): () => void; onSnapshot(listener: (snapshot: Snapshot) => void): () => void; onEvent(listener: (event: ControllerEvent) => void): () => void; onState(listener: (state: ConnectionState, gateway?: GatewayStatus) => void): () => void; sendRaw?(line: string): Promise<void>; onRaw?(listener: (line: string) => void): () => void }
export const unavailableCapabilities = (): Capabilities => ({ monitor: true, csv_logging: true, set_run_request: true, set_balancing_enabled: true, acknowledge_faults: true, get_rtc: true, get_device_info: true, read_register: true, get_diagnostic_report: true, runtime_configuration: true, wifi_configuration: false, mqtt_configuration: false, diagnostic_log_download: false, raw_terminal: false, firmware_update: false })
