export type CapabilityName = 'monitor' | 'csv_logging' | 'set_run_request' | 'clear_faults' | 'set_rtc' | 'read_register' | 'wifi_configuration' | 'diagnostic_log_download' | 'raw_terminal' | 'firmware_update'
export type Capabilities = Record<CapabilityName, boolean>
export type ServiceName = 'set_run_request' | 'clear_faults' | 'set_rtc' | 'read_register'
export type ServiceArguments = { set_run_request: { requested: boolean }; clear_faults: Record<string, never>; set_rtc: { unix_time_s: number }; read_register: { slave_index: number; register: number } }
export type ServiceResult = 'ok' | 'denied' | 'invalid' | 'busy' | 'transport_error'
export type ServiceResponse = { request_id: string; service: ServiceName; result: ServiceResult; data?: { slave_index: number; register: number; value: number } }
export type Status = { bms_state: number; hv_state: number; flags: number; slave_count: number; bms_active_faults: number; bms_latched_faults: number; hv_active_faults: number; hv_latched_faults: number; uptime_ms: number; measurements_fresh: boolean; run_request: boolean }
export type Snapshot = { status: Status; pack: { pack_voltage_uV: number; pack_current_raw: number; soc_raw: number; min_cell_uV: number; max_cell_uV: number; min_ntc_raw: number; max_ntc_raw: number; min_ic_raw: number; max_ic_raw: number }; cells: Array<{ slave_index: number; balance_mask: number; cell_voltage_uV: number[] }>; temperatures: Array<{ slave_index: number; ntc_raw: number[]; ic_temp_raw: number }> }
export type WifiNetwork = { ssid: string; rssi: number; secure: boolean }
export type WifiConfigurationResponse = { request_id: string; result: 'accepted' | 'error' | 'transport_error' }
export type WifiScanResponse = { request_id: string; result: 'ok' | 'busy' | 'rate_limited' | 'unavailable' | 'transport_error'; networks?: WifiNetwork[] }
export type GatewayStatus = { wifi_state: 'provisioning' | 'connecting' | 'connected' | 'recovery' | 'unavailable'; wifi_ssid?: string; setup_ap: { active: boolean; ssid?: string; address?: string }; uart_state: 'healthy' | 'lost' | 'starting'; mqtt_state: 'unavailable' | 'connecting' | 'connected' | 'lost'; diagnostic_log: { available: boolean; bytes: number } }
export type ConnectionState = 'disconnected' | 'connecting' | 'connected'
export interface BmsTransport { readonly label: string; connect(): Promise<void>; disconnect(): void; getConnectionState(): ConnectionState; getCapabilities(): Capabilities; request<S extends ServiceName>(service: S, args: ServiceArguments[S]): Promise<ServiceResponse>; configureWifi(ssid: string, password: string): Promise<WifiConfigurationResponse>; scanWifi(): Promise<WifiScanResponse>; onSnapshot(listener: (snapshot: Snapshot) => void): () => void; onEvent(listener: (event: { event_id: number; value: number; gateway_uptime_ms?: number }) => void): () => void; onState(listener: (state: ConnectionState, gateway?: GatewayStatus) => void): () => void; sendRaw?(line: string): Promise<void>; onRaw?(listener: (line: string) => void): () => void }
export const unavailableCapabilities = (): Capabilities => ({ monitor: true, csv_logging: true, set_run_request: true, clear_faults: true, set_rtc: true, read_register: true, wifi_configuration: false, diagnostic_log_download: false, raw_terminal: false, firmware_update: false })
