[platformio]
src_dir = main

[env:flexbms_gateway]
platform = espressif32@6.12.0
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio
upload_port = COM6
monitor_port = COM6