; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:default]
platform = ststm32
board = Nucleo_test
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
build_flags = 
	-D BOARD_BMS
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc"
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc"
	-I Inc
	-I Inc/Generated
	-Wl,--undefined,_printf_float
lib_deps = https://git.greenteamtwente.nl/hydro-electric/stm32g4-framework.git