; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:default]
platform = ststm32
board = Nucleo_test
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
platform_packages =
	toolchain-gccarmnoneeabi @^1.120301.0
build_flags = 
	-D BOARD_BMS
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc"
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc"
	-I Inc
	-I Inc/Generated
	-I Inc/Peripherals
	-Wl,--undefined,_printf_float

	# FreeRTOS related flags
	-mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp
	-specs=nosys.specs

lib_deps = 
	# FreeRTOS linker library
	https://github.com/mincrmatt12/stm32-platformio-freertos.git

	# Framework library
	https://hydrosurrogate.greenteamtwente.nl/hydro-electric/stm32-framework.git#V2

# Custom FreeRTOS configuration (for the linker library)
custom_freertos_config_location = Inc/FreeRTOSConfig.h
custom_freertos_cmsis_impl = CMSIS_RTOS_V2
custom_freertos_features = coroutines,timers,event_groups,stream_buffers