<script setup lang="ts">
import { computed, ref } from 'vue'
import { cellVoltageV, currentA, icCelsius, isFresh, ntcCelsius, setBits, socPercent, valueOrStale, bmsFaultNames, hvReasonNames } from '@/shared/model'
import { csvHeader, csvRow, downloadCsv } from '@/shared/csv'
import type { Snapshot } from '@/transports/Transport'
const props = defineProps<{ snapshot: Snapshot | null }>()
const lines = ref<string[]>([])
const fresh = computed(() => isFresh(props.snapshot))
function startLogging(): void { if (props.snapshot && fresh.value) lines.value = [csvHeader(props.snapshot).join(',')] }
function capture(): void { if (props.snapshot && fresh.value && lines.value.length) lines.value.push(csvRow(props.snapshot).join(',')) }
</script>
<template>
  <main v-if="snapshot" class="stack"><p v-if="!fresh" class="warning">Measurements are stale. Values below are not live zero data.</p><section class="cards"><div><b>BMS/HV</b><br>{{ snapshot.status.bms_state }} / {{ snapshot.status.hv_state }}</div><div><b>Run request</b><br>{{ snapshot.status.run_request ? 'requested' : 'off' }}</div><div><b>Pack voltage</b><br>{{ valueOrStale(`${cellVoltageV(snapshot.pack.pack_voltage_uV).toFixed(3)} V`, fresh) }}</div><div><b>Current</b><br>{{ valueOrStale(`${currentA(snapshot.pack.pack_current_raw).toFixed(2)} A`, fresh) }}</div><div><b>SoC</b><br>{{ valueOrStale(`${socPercent(snapshot.pack.soc_raw).toFixed(1)} %`, fresh) }}</div></section><section><h2>Faults and HV reasons</h2><p>Active BMS: {{ setBits(snapshot.status.bms_active_faults, bmsFaultNames).join(', ') || 'none' }}</p><p>Latched BMS: {{ setBits(snapshot.status.bms_latched_faults, bmsFaultNames).join(', ') || 'none' }}</p><p>Active HV: {{ setBits(snapshot.status.hv_active_faults, hvReasonNames).join(', ') || 'none' }}</p><p>Latched HV: {{ setBits(snapshot.status.hv_latched_faults, hvReasonNames).join(', ') || 'none' }}</p></section><section><h2>Cells and balancing</h2><div v-for="cell in snapshot.cells" :key="cell.slave_index"><b>Slave {{ cell.slave_index }}</b><span v-for="(value, index) in cell.cell_voltage_uV" :key="index" class="reading">C{{ index }} {{ valueOrStale(`${cellVoltageV(value).toFixed(4)} V`, fresh) }}{{ (cell.balance_mask & (1 << index)) ? ' ⚖' : '' }}</span></div></section><section><h2>Temperatures</h2><div v-for="temp in snapshot.temperatures" :key="temp.slave_index"><b>Slave {{ temp.slave_index }}</b><span v-for="(value, index) in temp.ntc_raw" :key="index" class="reading">NTC{{ index }} {{ valueOrStale(`${ntcCelsius(value).toFixed(1)} °C`, fresh) }}</span><span class="reading">IC {{ valueOrStale(`${icCelsius(temp.ic_temp_raw).toFixed(1)} °C`, fresh) }}</span></div></section><section><h2>Browser-local CSV</h2><button @click="startLogging" :disabled="!fresh">Start new CSV</button><button @click="capture" :disabled="!fresh || !lines.length">Capture row</button><button @click="downloadCsv(lines)" :disabled="lines.length < 2">Download CSV ({{ Math.max(0, lines.length - 1) }} rows)</button></section></main><main v-else><p>Connect to view BMS telemetry.</p></main>
</template>
