; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = Src

[env:default]
platform = ststm32
board = BMS_Master
framework = stm32cube
board_build.stm32cube.custom_config_header = yes
platform_packages =
	toolchain-gccarmnoneeabi @1.120301.0
extra_scripts = pre:add_hardfloat.py # Make sure to compile and link with FPU support ON
custom_freertos_isr_stack_size=0x100 # 256 words (1024 bytes)
build_flags = 
	-D configISR_STACK_SIZE_WORDS=${env:default.custom_freertos_isr_stack_size}
	-D COMMANDS       		; Allows you to interact with the FCCU over USB
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc"
	-I "${platformio.packages_dir}/framework-stm32cubeg4/Middlewares/ST/STM32_USB_Device_Library/Core/Inc"
	-I Inc
	-I Inc/Generated
	-I Inc/Peripherals

	# Compiler and linker flags
	-std=gnu++2b # use latest C++ standard (2023 experimental)
	-Wl,--undefined,_printf_float
	-Wno-volatile
	# Escalate the 'return type' warning to an error because it has cost us too many hours of debugging
	-Werror=return-type

	# FreeRTOS related flags
	-mthumb -larm_cortexM4lf_math
	-specs=nosys.specs

lib_deps = 
	# FreeRTOS linker library
	https://github.com/mincrmatt12/stm32-platformio-freertos.git

	# Framework library
	https://git.hydriventwente.nl/hydro-electric/stm32-framework.git


# Custom FreeRTOS configuration (for the linker library)
custom_freertos_config_location = Inc/Generated/FreeRTOSConfig.h
custom_freertos_config_heap_impl = newlib/heap_useNewlib_ST.c
custom_freertos_cmsis_impl = CMSIS_RTOS_V2
custom_freertos_features = coroutines,timers,event_groups,stream_buffers
monitor_port = COM4
